name: Build, upload & deploy

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 6 * * 2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Get version tag
        run: echo RELEASE=$(git tag) >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: ghcr.io/${{ github.repository }}:latest #ghcr.io/${{ github.repository }}:${{ env.RELEASE }}
